from app.models import Run, NetworkNode, NetworkEdge, Reroute

MOCK_RUNS = [
    Run(
        id=1,
        name="Forest_Night_01",
        date="2025-02-17",
        scenario="Tropical Night",
        model="BirdNET v2.4",
        hw="Radxa Zero",
        duration="24h",
        status="pass",
    ),
    Run(
        id=2,
        name="Forest_Dawn_03",
        date="2025-02-16",
        scenario="Dawn Chorus",
        model="BirdNET v2.3",
        hw="ESP32",
        duration="12h",
        status="warning",
    ),
    Run(
        id=3,
        name="Urban_Park_07",
        date="2025-02-15",
        scenario="Urban Noise",
        model="BirdNET v2.4",
        hw="Radxa Zero",
        duration="8h",
        status="pass",
    ),
    Run(
        id=4,
        name="Wetland_Rain_02",
        date="2025-02-14",
        scenario="Wetland Rain",
        model="BirdNET v2.3",
        hw="ESP32",
        duration="24h",
        status="fail",
    ),
    Run(
        id=5,
        name="Mountain_Clear_05",
        date="2025-02-13",
        scenario="Mountain Clear",
        model="BirdNET v2.4",
        hw="Radxa Zero",
        duration="16h",
        status="pass",
    ),
    Run(
        id=6,
        name="Forest_Storm_04",
        date="2025-02-12",
        scenario="Storm Event",
        model="BirdNET v2.2",
        hw="ESP32",
        duration="6h",
        status="warning",
    ),
    Run(
        id=7,
        name="Coastal_Night_01",
        date="2025-02-11",
        scenario="Coastal Night",
        model="BirdNET v2.4",
        hw="Radxa Zero",
        duration="24h",
        status="pass",
    ),
    Run(
        id=8,
        name="Desert_Day_02",
        date="2025-02-10",
        scenario="Desert Sparse",
        model="BirdNET v2.3",
        hw="ESP32",
        duration="12h",
        status="pass",
    ),
    Run(
        id=9,
        name="Jungle_Dense_06",
        date="2025-02-09",
        scenario="Dense Canopy",
        model="BirdNET v2.4",
        hw="Radxa Zero",
        duration="24h",
        status="warning",
    ),
    Run(
        id=10,
        name="River_Valley_03",
        date="2025-02-08",
        scenario="River Valley",
        model="BirdNET v2.2",
        hw="ESP32",
        duration="8h",
        status="pass",
    ),
]

MOCK_NODES = [
    NetworkNode(
        id="CMD",
        label="Command Center",
        role="command",
        x=0.50,
        y=0.10,
        battery=100,
        drain=0.1,
        traffic=95,
        health="good",
        packetsIn=4820,
        packetsOut=312,
        retries=24,
        collisions=8,
        aiDet=127,
        events=["System boot", "All nodes online", "12 reroutes"],
        powerBreakdown={"radio": 15, "processor": 5, "mic": 0},
    ),
    NetworkNode(
        id="R1",
        label="Shaman II-1",
        role="relay",
        x=0.28,
        y=0.30,
        battery=23,
        drain=3.2,
        traffic=89,
        health="critical",
        packetsIn=2640,
        packetsOut=2580,
        retries=186,
        collisions=42,
        aiDet=0,
        events=["High relay load", "Battery warning"],
        powerBreakdown={"radio": 55, "processor": 30, "mic": 15},
        children=["S1", "S2", "S3", "S4"],
    ),
    NetworkNode(
        id="R2",
        label="Shaman II-2",
        role="relay",
        x=0.72,
        y=0.28,
        battery=34,
        drain=2.8,
        traffic=82,
        health="warning",
        packetsIn=2180,
        packetsOut=2120,
        retries=148,
        collisions=35,
        aiDet=0,
        events=["Relay congestion", "Packet loss spike"],
        powerBreakdown={"radio": 50, "processor": 32, "mic": 18},
        children=["S5", "S6", "S7"],
    ),
    NetworkNode(
        id="R3",
        label="Shaman II-3",
        role="relay",
        x=0.50,
        y=0.48,
        battery=61,
        drain=1.4,
        traffic=45,
        health="good",
        packetsIn=980,
        packetsOut=940,
        retries=52,
        collisions=11,
        aiDet=0,
        events=["Normal operation"],
        powerBreakdown={"radio": 40, "processor": 35, "mic": 25},
        children=["S8", "S9", "S10"],
    ),
    NetworkNode(
        id="R4",
        label="Shaman II-4",
        role="relay",
        x=0.16,
        y=0.55,
        battery=55,
        drain=1.6,
        traffic=52,
        health="warning",
        packetsIn=1120,
        packetsOut=1080,
        retries=68,
        collisions=15,
        aiDet=0,
        events=["Moderate load"],
        powerBreakdown={"radio": 45, "processor": 33, "mic": 22},
        children=["S11"],
    ),
    NetworkNode(
        id="S1",
        label="Shaman I-01",
        role="sensor",
        x=0.10,
        y=0.36,
        battery=72,
        drain=0.8,
        traffic=15,
        health="good",
        packetsIn=42,
        packetsOut=280,
        retries=12,
        collisions=3,
        aiDet=18,
        events=["8 gunshot", "6 bird"],
        powerBreakdown={"radio": 30, "processor": 25, "mic": 45},
        parent="R1",
    ),
    NetworkNode(
        id="S2",
        label="Shaman I-02",
        role="sensor",
        x=0.14,
        y=0.20,
        battery=68,
        drain=0.9,
        traffic=18,
        health="good",
        packetsIn=38,
        packetsOut=310,
        retries=15,
        collisions=4,
        aiDet=22,
        events=["12 bird", "6 chainsaw"],
        powerBreakdown={"radio": 28, "processor": 27, "mic": 45},
        parent="R1",
    ),
    NetworkNode(
        id="S3",
        label="Shaman I-03",
        role="sensor",
        x=0.08,
        y=0.50,
        battery=45,
        drain=1.1,
        traffic=22,
        health="warning",
        packetsIn=52,
        packetsOut=340,
        retries=28,
        collisions=8,
        aiDet=14,
        events=["High retries", "9 bird"],
        powerBreakdown={"radio": 35, "processor": 22, "mic": 43},
        parent="R1",
    ),
    NetworkNode(
        id="S4",
        label="Shaman I-04",
        role="sensor",
        x=0.22,
        y=0.42,
        battery=78,
        drain=0.7,
        traffic=12,
        health="good",
        packetsIn=36,
        packetsOut=260,
        retries=8,
        collisions=2,
        aiDet=11,
        events=["Normal", "7 bird"],
        powerBreakdown={"radio": 26, "processor": 24, "mic": 50},
        parent="R1",
    ),
    NetworkNode(
        id="S5",
        label="Shaman I-05",
        role="sensor",
        x=0.86,
        y=0.17,
        battery=70,
        drain=0.8,
        traffic=16,
        health="good",
        packetsIn=40,
        packetsOut=290,
        retries=14,
        collisions=3,
        aiDet=19,
        events=["10 bird", "5 gunshot"],
        powerBreakdown={"radio": 30, "processor": 25, "mic": 45},
        parent="R2",
    ),
    NetworkNode(
        id="S6",
        label="Shaman I-06",
        role="sensor",
        x=0.88,
        y=0.38,
        battery=64,
        drain=0.9,
        traffic=20,
        health="good",
        packetsIn=48,
        packetsOut=320,
        retries=18,
        collisions=5,
        aiDet=16,
        events=["8 bird", "5 voice"],
        powerBreakdown={"radio": 32, "processor": 23, "mic": 45},
        parent="R2",
    ),
    NetworkNode(
        id="S7",
        label="Shaman I-07",
        role="sensor",
        x=0.78,
        y=0.44,
        battery=58,
        drain=1.0,
        traffic=24,
        health="warning",
        packetsIn=55,
        packetsOut=350,
        retries=22,
        collisions=7,
        aiDet=13,
        events=["Moderate retries", "8 bird"],
        powerBreakdown={"radio": 34, "processor": 24, "mic": 42},
        parent="R2",
    ),
    NetworkNode(
        id="S8",
        label="Shaman I-08",
        role="sensor",
        x=0.38,
        y=0.65,
        battery=80,
        drain=0.6,
        traffic=10,
        health="good",
        packetsIn=30,
        packetsOut=240,
        retries=6,
        collisions=1,
        aiDet=8,
        events=["Low traffic", "5 bird"],
        powerBreakdown={"radio": 25, "processor": 25, "mic": 50},
        parent="R3",
    ),
    NetworkNode(
        id="S9",
        label="Shaman I-09",
        role="sensor",
        x=0.56,
        y=0.66,
        battery=75,
        drain=0.7,
        traffic=14,
        health="good",
        packetsIn=35,
        packetsOut=270,
        retries=10,
        collisions=2,
        aiDet=10,
        events=["Normal", "6 bird"],
        powerBreakdown={"radio": 28, "processor": 24, "mic": 48},
        parent="R3",
    ),
    NetworkNode(
        id="S10",
        label="Shaman I-10",
        role="sensor",
        x=0.62,
        y=0.56,
        battery=82,
        drain=0.6,
        traffic=9,
        health="good",
        packetsIn=28,
        packetsOut=230,
        retries=5,
        collisions=1,
        aiDet=6,
        events=["Low load", "4 bird"],
        powerBreakdown={"radio": 24, "processor": 26, "mic": 50},
        parent="R3",
    ),
    NetworkNode(
        id="S11",
        label="Shaman I-11",
        role="sensor",
        x=0.24,
        y=0.70,
        battery=42,
        drain=1.2,
        traffic=28,
        health="warning",
        packetsIn=60,
        packetsOut=380,
        retries=32,
        collisions=10,
        aiDet=20,
        events=["High detection"],
        powerBreakdown={"radio": 36, "processor": 22, "mic": 42},
        parent="R4",
    ),
]

MOCK_EDGES = [
    NetworkEdge(frm="CMD", to="R1", congestion=88, packetLoss=6.2, retries=86, collisions=22, avgDelay=68, reroutes=4, latency=52),
    NetworkEdge(frm="CMD", to="R2", congestion=80, packetLoss=5.1, retries=72, collisions=18, avgDelay=55, reroutes=3, latency=48),
    NetworkEdge(frm="CMD", to="R3", congestion=35, packetLoss=1.8, retries=22, collisions=5, avgDelay=28, reroutes=1, latency=32),
    NetworkEdge(frm="R1", to="S1", congestion=42, packetLoss=2.4, retries=18, collisions=5, avgDelay=32, reroutes=1, latency=28),
    NetworkEdge(frm="R1", to="S2", congestion=48, packetLoss=2.8, retries=22, collisions=6, avgDelay=35, reroutes=1, latency=30),
    NetworkEdge(frm="R1", to="S3", congestion=55, packetLoss=3.5, retries=30, collisions=9, avgDelay=42, reroutes=2, latency=38),
    NetworkEdge(frm="R1", to="S4", congestion=38, packetLoss=1.9, retries=14, collisions=3, avgDelay=25, reroutes=0, latency=22),
    NetworkEdge(frm="R1", to="R4", congestion=52, packetLoss=3.0, retries=28, collisions=7, avgDelay=38, reroutes=2, latency=35),
    NetworkEdge(frm="R2", to="S5", congestion=44, packetLoss=2.5, retries=20, collisions=5, avgDelay=30, reroutes=1, latency=26),
    NetworkEdge(frm="R2", to="S6", congestion=50, packetLoss=3.0, retries=24, collisions=6, avgDelay=36, reroutes=1, latency=32),
    NetworkEdge(frm="R2", to="S7", congestion=58, packetLoss=3.8, retries=28, collisions=8, avgDelay=44, reroutes=2, latency=40),
    NetworkEdge(frm="R3", to="S8", congestion=18, packetLoss=0.8, retries=6, collisions=1, avgDelay=15, reroutes=0, latency=14),
    NetworkEdge(frm="R3", to="S9", congestion=22, packetLoss=1.0, retries=8, collisions=2, avgDelay=18, reroutes=0, latency=16),
    NetworkEdge(frm="R3", to="S10", congestion=15, packetLoss=0.6, retries=4, collisions=1, avgDelay=12, reroutes=0, latency=12),
    NetworkEdge(frm="R4", to="S11", congestion=60, packetLoss=4.2, retries=34, collisions=10, avgDelay=48, reroutes=3, latency=42),
    NetworkEdge(frm="R4", to="S3", congestion=30, packetLoss=1.5, retries=12, collisions=3, avgDelay=22, reroutes=1, latency=20),
    NetworkEdge(frm="R3", to="R2", congestion=28, packetLoss=1.2, retries=10, collisions=2, avgDelay=20, reroutes=0, latency=18),
    NetworkEdge(frm="R3", to="R1", congestion=32, packetLoss=1.6, retries=14, collisions=3, avgDelay=24, reroutes=1, latency=22),
]

MOCK_REROUTES = [
    Reroute(frm="S3", to="R4"),
    Reroute(frm="S7", to="R3"),
    Reroute(frm="S11", to="R3"),
]
